"""empty message

Revision ID: a71aaa15b762
Revises: 0f8b574e137a
Create Date: 2025-01-29 15:58:19.223898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a71aaa15b762'
down_revision = '0f8b574e137a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('country', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('lat', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('long', sa.Integer(), nullable=False))

    with op.batch_alter_table('experience', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('experience', schema=None) as batch_op:
        batch_op.drop_column('image')

    with op.batch_alter_table('country', schema=None) as batch_op:
        batch_op.drop_column('long')
        batch_op.drop_column('lat')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
